dbtlearn:
  outputs:
    dev:
      account: LJDFUJU-IM69969
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: raw
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
  